apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: polaris-demo
  namespace: rehan
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: polaris-demo
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/language: "java"
    workload-intent: code-analysis
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_server_address
    value: ssh://git@github.com
  - name: gitops_ssh_secret
    value: gitops-ssh
  - name: gitops_repository_owner
    value: Mpluya
  - name: gitops_repository_name
    value: config-post-polaris
  - name: gitops_branch
    value: main
  source:
    git:
      url: ssh://git@github.com/Mpluya/polaris-demo
      ref:
        branch: main
