apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: polaris-demo
  namespace: rehan
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: polaris-demo
    apps.tanzu.vmware.com/has-tests: "true"
    workload-intent: code-analysis
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/Mpluya/polaris-demo
      ref:
        branch: main
